name: Call a reusable workflow(inside repo)
on:
  workflow_dispatch:

jobs:
  job1:
    permissions:
      contents: read
      pull-requests: write
    uses: MareMare/try-github-reusable-workflows/.github/workflows/reusable-workflow-example.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: 📝 print message
      run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
